pipeline {
    agent any

    parameters {
        string(defaultValue: '', description: 'This is for docker image tag', name: 'IMAGE_TAG')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']],
                    userRemoteConfigs: [[url: 'https://github.com/ashokmnr/dockerfile-examples.git']]])
            }
        }
        stage("Docker build") {
            steps {
                sh """
                    whoami
                    docker build -t ${IMAGE_TAG} tomcat-dockerfile/.
                """
            }
        }
        stage("Docker images push to ecr") {
            steps {
                sh """
                    echo "push to ecr"
                """
            }
        }
    }
}