pipeline {
    agent any

    parameters {

        string(defaultValue: '', description: 'This is for docker image tag', name: 'IMAGE_TAG')
        string(defaultValue: '', description: 'This is for docker image tag', name: 'TAG_NAME')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'refs/tags/${TAG_NAME}']],
                    userRemoteConfigs: [[url: 'https://github.com/ashokmnr/dockerfile-examples.git']]])
            }
        }

        stage("Build Image") {
            steps {
                sh """
                    docker build -t 393492168443.dkr.ecr.us-east-1.amazonaws.com/dev-images:${IMAGE_TAG} tomcat-dockerfile/.
                """
            }
        }
        stage("Docker images push to ecr") {
            steps {
                sh """
                    echo "push to ecr"
                """
            }
        }
    }
    post {
        always {
            script {
                manager.addShortText("${params.IMAGE_TAG}")
                manager.addShortText("${params.TAG_NAME}")
            }
            echo 'One way or another, I have finished'
             deleteDir() /* clean up our workspace */
        }
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
}