pipeline {
    agent any

    parameters {
        string(defaultValue: '', description: 'This is for docker image tag', name: 'IMAGE_TAG')
    }

    stage('Checkout') {
        steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']],
                userRemoteConfigs: [[url: 'http://git-server/user/repository.git']]])
        }
    }
    stage("Docker build") {
        sh """
            docker build -t ${IMAGE_TAG} .
        """
    }
    stage("Docker images push to ecr")
    sh """
        echo "push to ecr"
    """

}